# Generated by Django 4.2.11 on 2025-08-09 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('night_occurred', models.IntegerField()),
                ('text_clarity', models.FloatField(default=1.0)),
                ('response_coherence', models.FloatField(default=1.0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.character')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.location')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(blank=True, max_length=100)),
                ('witness_name', models.CharField(max_length=200)),
                ('witness_size', models.CharField(default='thumb', max_length=50)),
                ('witness_mount', models.CharField(blank=True, max_length=100)),
                ('night_count', models.IntegerField(default=1)),
                ('total_weight', models.FloatField(default=0.0)),
                ('movement_speed', models.FloatField(default=1.0)),
                ('world_entropy', models.FloatField(default=0.0)),
                ('text_degradation', models.FloatField(default=0.0)),
                ('color_loss', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_action_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('map_tears', models.JSONField(default=list)),
                ('map_burns', models.JSONField(default=list)),
                ('map_blood', models.JSONField(default=list)),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.location')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worlds.world')),
            ],
            options={
                'ordering': ['-last_action_at'],
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('knowledge_type', models.CharField(choices=[('whisper', 'Whisper (Ephemeral)'), ('mark', 'Mark (Physical)'), ('oath', 'Oath (Binding)')], max_length=50)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('base_weight', models.FloatField(default=1.0)),
                ('truth_multiplier', models.FloatField(default=1.0)),
                ('personal_multiplier', models.FloatField(default=1.0)),
                ('total_weight', models.FloatField(default=1.0)),
                ('is_truth', models.BooleanField(default=True)),
                ('is_terrible', models.BooleanField(default=False)),
                ('involves_self', models.BooleanField(default=False)),
                ('has_been_shared', models.BooleanField(default=False)),
                ('discovered_time', models.DateTimeField(auto_now_add=True)),
                ('night_discovered', models.IntegerField(default=1)),
                ('discovered_at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.location')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='game.gamesession')),
            ],
            options={
                'ordering': ['-discovered_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(choices=[('witness', 'Witness'), ('character', 'Character'), ('narrator', 'Narrator')], max_length=50)),
                ('original_content', models.TextField()),
                ('degraded_content', models.TextField()),
                ('degradation_level', models.FloatField(default=0.0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.conversation')),
                ('knowledge_gained', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.knowledge')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discovery_type', models.CharField(choices=[('truth', 'Hidden Truth'), ('death', 'Character Death'), ('betrayal', 'Betrayal'), ('treaty_broken', 'Treaty Broken'), ('location_lost', 'Location Lost')], max_length=50)),
                ('description', models.TextField()),
                ('world_impact', models.TextField()),
                ('map_impact', models.CharField(choices=[('tear', 'Tore the Map'), ('burn', 'Burned the Map'), ('blood', 'Bloodied the Map'), ('none', 'No Map Impact')], default='none', max_length=50)),
                ('impact_location', models.JSONField(default=dict)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('night_discovered', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='game.gamesession')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='game.gamesession'),
        ),
    ]
