# Generated by Django 4.2.11 on 2025-08-09 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('role', models.CharField(blank=True, max_length=100)),
                ('has_agency', models.BooleanField(default=True)),
                ('power_level', models.IntegerField(default=5)),
                ('is_witness_candidate', models.BooleanField(default=False)),
                ('alive', models.BooleanField(default=True)),
                ('memory_intact', models.FloatField(default=1.0)),
                ('known_truths', models.JSONField(default=list)),
                ('spoken_lies', models.JSONField(default=list)),
                ('personality_prompt', models.TextField(blank=True)),
                ('speech_pattern', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('size_scale', models.CharField(choices=[('microscopic', 'Microscopic'), ('tiny', 'Tiny'), ('small', 'Small'), ('human', 'Human Scale'), ('large', 'Large'), ('vast', 'Vast')], default='human', max_length=50)),
                ('integrity', models.FloatField(default=1.0)),
                ('color_saturation', models.FloatField(default=1.0)),
                ('clarity', models.FloatField(default=1.0)),
                ('has_been_witnessed', models.BooleanField(default=False)),
                ('last_witnessed', models.DateTimeField(blank=True, null=True)),
                ('witness_count', models.IntegerField(default=0)),
                ('connected_to', models.ManyToManyField(blank=True, to='worlds.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_type', models.CharField(choices=[('onlyworlds', 'OnlyWorlds Import'), ('text', 'Parsed Text'), ('manual', 'Manual Creation')], max_length=50)),
                ('source_reference', models.TextField(blank=True)),
                ('witness_config', models.JSONField(default=dict)),
                ('resource_types', models.JSONField(default=dict)),
                ('degradation_pattern', models.JSONField(default=dict)),
                ('hidden_truth', models.TextField(blank=True)),
                ('onlyworlds_api_key', models.CharField(blank=True, max_length=100)),
                ('onlyworlds_pin', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('times_witnessed', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treaty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('is_broken', models.BooleanField(default=False)),
                ('terms', models.JSONField(default=list)),
                ('consequences', models.TextField(blank=True)),
                ('strength', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broken_at', models.DateTimeField(blank=True, null=True)),
                ('parties', models.ManyToManyField(related_name='treaties', to='worlds.character')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treaties', to='worlds.world')),
            ],
            options={
                'verbose_name_plural': 'Treaties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('tiny', 'Tiny - fits in palm'), ('small', 'Small - can be carried'), ('medium', 'Medium - requires effort'), ('large', 'Large - immovable')], default='small', max_length=50)),
                ('weight', models.FloatField(default=1.0)),
                ('resource_type', models.CharField(choices=[('ephemeral', 'Ephemeral (whispers, rumors)'), ('physical', 'Physical (marks, scars)'), ('binding', 'Binding (oaths, contracts)')], default='physical', max_length=50)),
                ('condition', models.FloatField(default=1.0)),
                ('hidden', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.location')),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.character')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='worlds.world')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='worlds.world'),
        ),
        migrations.AddField(
            model_name='character',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='worlds.world'),
        ),
    ]
