# Generated by Django 4.2.11 on 2025-08-09 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('memory_type', models.CharField(choices=[('fact', 'Fact'), ('conversation', 'Conversation'), ('observation', 'Observation'), ('feeling', 'Feeling'), ('secret', 'Secret')], max_length=50)),
                ('content', models.TextField()),
                ('clarity', models.FloatField(default=1.0)),
                ('accessibility', models.FloatField(default=1.0)),
                ('is_suppressed', models.BooleanField(default=False)),
                ('is_false', models.BooleanField(default=False)),
                ('formed_at', models.DateTimeField(auto_now_add=True)),
                ('last_recalled', models.DateTimeField(blank=True, null=True)),
                ('recall_count', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='worlds.character')),
            ],
            options={
                'ordering': ['-formed_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('local', 'Local Model')], max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('endpoint', models.URLField(blank=True)),
                ('model_name', models.CharField(max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalityTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('base_prompt', models.TextField()),
                ('speech_patterns', models.JSONField(default=list)),
                ('vocabulary_level', models.CharField(choices=[('simple', 'Simple'), ('normal', 'Normal'), ('eloquent', 'Eloquent'), ('archaic', 'Archaic'), ('broken', 'Broken')], default='normal', max_length=50)),
                ('truthfulness', models.FloatField(default=0.5)),
                ('memory_quality', models.FloatField(default=0.8)),
                ('paranoia', models.FloatField(default=0.3)),
                ('despair', models.FloatField(default=0.2)),
                ('memory_decay_rate', models.FloatField(default=0.01)),
                ('speech_decay_rate', models.FloatField(default=0.02)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_state', models.JSONField(default=dict)),
                ('world_state', models.JSONField(default=dict)),
                ('relationship_state', models.JSONField(default=dict)),
                ('degradation_level', models.FloatField(default=0.0)),
                ('coherence_target', models.FloatField(default=1.0)),
                ('truth_tendency', models.FloatField(default=0.5)),
                ('suppressed_topics', models.JSONField(default=list)),
                ('active_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessible_memories', models.ManyToManyField(to='llm.charactermemory')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.conversation')),
            ],
        ),
    ]
