# Generated by Django 4.2.11 on 2025-08-09 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_type', models.CharField(max_length=50)),
                ('extraction_rules', models.JSONField(default=dict)),
                ('entity_patterns', models.JSONField(default=dict)),
                ('witness_criteria', models.JSONField(default=dict)),
                ('resource_mapping', models.JSONField(default=dict)),
                ('times_used', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParseSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='parse_sources/')),
                ('source_text', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF Document'), ('txt', 'Plain Text'), ('html', 'HTML/Web Page'), ('docx', 'Word Document'), ('epub', 'EPUB Book'), ('manual', 'Manual Input')], max_length=50)),
                ('world_name', models.CharField(max_length=200)),
                ('witness_type', models.CharField(choices=[('auto', 'Auto-detect witness'), ('smallest', 'Find smallest character'), ('observer', 'Find pure observer'), ('child', 'Find child character'), ('animal', 'Find animal observer'), ('object', 'Create object witness')], default='auto', max_length=50)),
                ('extraction_complete', models.BooleanField(default=False)),
                ('entities_identified', models.BooleanField(default=False)),
                ('witness_selected', models.BooleanField(default=False)),
                ('resources_defined', models.BooleanField(default=False)),
                ('world_created', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True)),
                ('entities', models.JSONField(default=dict)),
                ('witness_config', models.JSONField(default=dict)),
                ('resource_mapping', models.JSONField(default=dict)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.world')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('character', 'Character'), ('location', 'Location'), ('object', 'Object'), ('event', 'Event'), ('concept', 'Concept'), ('treaty', 'Treaty/Agreement')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('properties', models.JSONField(default=dict)),
                ('mentions', models.JSONField(default=list)),
                ('relationships', models.JSONField(default=list)),
                ('power_level', models.IntegerField(blank=True, null=True)),
                ('size_scale', models.CharField(blank=True, max_length=50)),
                ('importance_score', models.FloatField(default=0.5)),
                ('is_witness_candidate', models.BooleanField(default=False)),
                ('witness_score', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_entities', to='parser.parsesession')),
            ],
            options={
                'ordering': ['entity_type', 'name'],
            },
        ),
    ]
